name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: sanjaysam410
          file: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: darkhub
          no-frame: true
          max-rows: 1
          max-cols: 7

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trophy.svg
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub Trophies" && git push)
